compile:
	javac Assembler.java
	javac Proessor_Window.java
	javac Memory_Window.java
	javac Visualizer_Window.java
	javac Simulator.java
example1:
	java Assembler example1
	java Simulator example1

example2:
	java Assembler example2
	java Simulator example2

example3:
	java Assembler example3
	java Simulator example3
